# Generated by Django 4.1.3 on 2022-12-06 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0002_material_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
