# Generated by Django 4.1.3 on 2022-12-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0003_infill_color_available_material_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.CharField(default='todo', max_length=256),
            preserve_default=False,
        ),
    ]
