# Generated by Django 4.1.3 on 2023-02-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0005_alter_color_managers_alter_infill_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='printing_speed',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
