# Generated by Django 4.1.3 on 2023-02-19 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0006_material_printing_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('available', models.BooleanField()),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.material')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
