# Generated by Django 4.1.3 on 2023-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0007_spool'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spool',
            constraint=models.UniqueConstraint(fields=('material', 'color'), name='spool_material_color_unique_constraint'),
        ),
    ]
