# Generated by Django 4.1.3 on 2023-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0008_spool_spool_material_color_unique_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='price',
            new_name='filament_cost',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='density',
            new_name='filament_density',
        ),
        migrations.RemoveField(
            model_name='material',
            name='printing_speed',
        ),
        migrations.AddField(
            model_name='material',
            name='extrusion_multiplier',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='filament_deretract_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='filament_max_volumetric_speed',
            field=models.FloatField(default=1.35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='retract_length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='retract_lift',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
