# Generated by Django 4.2 on 2023-06-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0009_rename_price_material_filament_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfillWallsCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.infill')),
                ('walls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.walls')),
            ],
        ),
    ]
