# Generated by Django 4.2 on 2023-06-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0028_printunitinfill_printunitwall_and_more'),
        ('filament', '0010_walls_infillwallscombination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infillwallscombination',
            name='infill',
        ),
        migrations.RemoveField(
            model_name='infillwallscombination',
            name='walls',
        ),
        migrations.DeleteModel(
            name='Infill',
        ),
        migrations.DeleteModel(
            name='InfillWallsCombination',
        ),
        migrations.DeleteModel(
            name='Walls',
        ),
    ]
