# Generated by Django 4.1.3 on 2022-12-29 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0015_rename_billing_addresses_userprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userprofile')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
