# Generated by Django 4.1.3 on 2022-12-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_rename_billing_addresses_userprofile_billing_address_and_more'),
        ('modeling_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingorder',
            name='contact_email',
            field=models.EmailField(default='a@adf.asdf', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelingorder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userprofile'),
        ),
    ]
