# Generated by Django 4.1.3 on 2023-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0002_modelingorder_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingorder',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=69, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelingorder',
            name='status',
            field=models.CharField(choices=[('reviewing', 'Reviewing'), ('estimating_price', 'Estimating price'), ('rejected', 'Rejected'), ('awaiting_payment', 'Awaiting Payment'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='reviewing', max_length=16),
        ),
    ]
