# Generated by Django 4.1.3 on 2023-01-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0003_modelingorder_estimated_price_modelingorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingorder',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
