# Generated by Django 4.1.3 on 2023-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0004_alter_modelingorder_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingorder',
            name='status',
            field=models.CharField(choices=[('reviewing', 'Reviewing'), ('estimating_price', 'Estimating price'), ('awaiting_payment', 'Awaiting payment'), ('rejected', 'Rejected'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='reviewing', max_length=16),
        ),
    ]
