# Generated by Django 4.2 on 2023-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0006_itemattribute_itemtype_modelingorder_item_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='description',
            field=models.CharField(default='todo description', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='icon_name',
            field=models.CharField(default='icon:todo', max_length=64),
            preserve_default=False,
        ),
    ]
