# Generated by Django 4.2 on 2023-06-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0007_ordertype_itemattribute_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattribute',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
