# Generated by Django 4.2 on 2023-07-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0008_alter_itemattribute_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingorder',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeling_order.ordertype'),
        ),
        migrations.AlterField(
            model_name='modelingorder',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT will be added on this price', max_digits=12, null=True),
        ),
    ]
