# Generated by Django 4.2 on 2023-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_order', '0009_modelingorder_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='description',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
    ]
