version: '3.7'

services:

  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./data/postgres/database_scripts/001_create_database.sql:/docker-entrypoint-initdb.d/001_create_database.sql
    env_file:
      - .env.production.db

  web:
    build: .
    working_dir: /home/spoolio_web_user/app

    # todo add gunicorn logging files (permission denied) --access-logfile /var/log/access_file_g.log --error-logfile /var/log/error_file_g.log

    command: bash -c "gunicorn spoolio_backend.asgi:application --bind 0.0.0.0:8000 --capture-output --enable-stdio-inheritance -k uvicorn.workers.UvicornWorker"
    volumes:
      - .:/home/spoolio_web_user/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - static_volume:/var/www/toqo.app/static
      # - media_volume:/var/www/toqo.app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env.production
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 2h"
      ofelia.job-exec.datecron.command: "python3 manage.py dbbackup"
      ofelia.job-exec.datecron.container: 'web'
      ofelia.job-exec.datecron.user: 'spoolio_web_user' # without it there is not access to installed user packages (Django eg)
    links:
      - redis
    entrypoint: [ "/home/spoolio_web_user/app/entrypoint.sh" ]

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./data/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro

      - type: bind
        source: ./data/nginx/nginx.conf
        target: /etc/nginx/nginx.conf

    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www/:/var/www/certbot/:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: on-failure

  celery:
    restart: always
    build:
      context: .
    command: celery -A spoolio_backend worker -l INFO
    volumes:
      - .:/home/spoolio_web_user/app
    env_file:
      - .env.production.celery
      - .env.production
      - .env.production.db
    working_dir: /home/spoolio_web_user/app
    links:
      - db
      - redis
      - web

volumes:
  postgres_data:
