# Generated by Django 4.1.3 on 2022-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='print_order.orderattachmentfile'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('paid', 'Paid'), ('shipped', 'Shipped')], default='pending', max_length=16),
        ),
    ]
