# Generated by Django 4.1.3 on 2022-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0002_alter_printorder_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='print_order.orderattachmentfile'),
        ),
    ]
