# Generated by Django 4.1.3 on 2022-12-04 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0004_attachmentfile_attachmentimage_color_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
