# Generated by Django 4.1.3 on 2022-12-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0001_initial'),
        ('print_order', '0005_material_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.color'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.material'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
