# Generated by Django 4.1.3 on 2022-12-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_address_alter_userprofile_phone_number'),
        ('print_order', '0006_alter_orderunit_color_alter_orderunit_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userprofile'),
        ),
    ]
