# Generated by Django 4.1.3 on 2022-12-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0003_infill_color_available_material_available'),
        ('print_order', '0007_alter_printorder_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='infill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament.infill'),
        ),
    ]
