# Generated by Django 4.1.3 on 2022-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0008_alter_orderunit_infill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='file',
            field=models.FileField(default=None, upload_to='print_order_files'),
            preserve_default=False,
        ),
    ]
