# Generated by Django 4.1.3 on 2022-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0009_orderunit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='length_unit',
            field=models.CharField(default='mms', max_length=8),
            preserve_default=False,
        ),
    ]
