# Generated by Django 4.1.3 on 2022-12-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0011_shippingmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentfile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachmentimage',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
        migrations.DeleteModel(
            name='AttachmentFile',
        ),
        migrations.DeleteModel(
            name='AttachmentImage',
        ),
    ]
