# Generated by Django 4.1.3 on 2022-12-30 22:57

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0012_remove_attachmentfile_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderunit',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
