# Generated by Django 4.1.3 on 2022-12-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_attachmentfile_managers_and_more'),
        ('print_order', '0013_alter_orderunit_managers_orderunit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='billing_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='common.billingaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='contact_email',
            field=models.EmailField(default='abc@def.ghi', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='common.shippingaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.shippingmethod'),
        ),
    ]
