# Generated by Django 4.1.3 on 2023-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0014_printorder_billing_address_printorder_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=420, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printorder',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('rejected', 'Rejected'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='awaiting_payment', max_length=16),
        ),
    ]
