# Generated by Django 4.1.3 on 2023-02-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0008_spool_spool_material_color_unique_constraint'),
        ('print_order', '0016_remove_orderunit_color_remove_orderunit_infill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='spool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filament.spool'),
            preserve_default=False,
        ),
    ]
