# Generated by Django 4.1.3 on 2023-02-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0008_spool_spool_material_color_unique_constraint'),
        ('print_order', '0017_alter_orderunit_spool'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='infill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filament.infill'),
            preserve_default=False,
        ),
    ]
