# Generated by Django 4.1.3 on 2023-03-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0018_orderunit_infill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=42.69, max_digits=12),
            preserve_default=False,
        ),
    ]
