# Generated by Django 4.1.3 on 2023-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0019_orderunit_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='model_dimensions',
            field=models.CharField(default=(69, 420, 1488), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunit',
            name='model_volume',
            field=models.FloatField(default=0.69),
            preserve_default=False,
        ),
    ]
