# Generated by Django 4.1.3 on 2023-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0020_orderunit_model_dimensions_orderunit_model_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='estimated_time',
            field=models.PositiveIntegerField(default=69420),
            preserve_default=False,
        ),
    ]
