# Generated by Django 4.1.3 on 2023-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0021_orderunit_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='estimated_time',
            field=models.PositiveIntegerField(default=42690),
            preserve_default=False,
        ),
    ]
