# Generated by Django 4.1.3 on 2023-03-08 13:58

from django.db import migrations, models
import spoolio_backend.libs.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0022_printorder_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='file',
            field=models.FileField(storage=spoolio_backend.libs.storage_backends.PrivateMediaStorage(), upload_to='print_order_files'),
        ),
    ]
