# Generated by Django 4.1.3 on 2023-04-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0024_alter_printorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='model_rotation',
            field=models.CharField(default='0,0,0', help_text='Rotation chosen by user on frontend. Format: "x,y,z"', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunit',
            name='optimal_rotation',
            field=models.CharField(default='0,0,0', help_text='Rotation determined by Threejs on frontend to be optimal. Format: "x,y,z"', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunit',
            name='rotation_unit',
            field=models.CharField(default='degrees', help_text='degrees or radians', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderunit',
            name='use_optimal_rotation',
            field=models.BooleanField(default=True, help_text='If true then optimal_rotation should bu used, else use model_rotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='length_unit',
            field=models.CharField(help_text='mms or inches', max_length=8),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='model_dimensions',
            field=models.CharField(help_text='Dimensions with length_unit unit.', max_length=128),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='model_volume',
            field=models.FloatField(help_text='Volume with length_unit unit. Format: "x,y,z"'),
        ),
    ]
