# Generated by Django 4.1.3 on 2023-04-18 07:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0025_orderunit_model_rotation_orderunit_optimal_rotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='print_unit_screenshots/'),
        ),
    ]
