# Generated by Django 4.1.3 on 2023-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0026_orderunit_screenshot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderunit',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='printorder',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='orderunit',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='is_deleted',
        ),
    ]
