# Generated by Django 4.2 on 2023-06-02 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0027_alter_orderunit_managers_alter_printorder_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintUnitInfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintUnitWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orderunit',
            name='infill',
        ),
        migrations.CreateModel(
            name='PrintUnitInfillWallCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('infill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitinfill')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitwall')),
            ],
        ),
    ]
