# Generated by Django 4.2 on 2023-06-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0028_printunitinfill_printunitwall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='infill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitinfill'),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='wall',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitwall'),
        ),
    ]
