# Generated by Django 4.2 on 2023-06-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0029_orderunit_infill_orderunit_wall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printunitwall',
            old_name='count',
            new_name='amount',
        ),
    ]
