# Generated by Django 4.2 on 2023-06-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0030_rename_count_printunitwall_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='infill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitinfill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='wall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitwall'),
            preserve_default=False,
        ),
    ]
