# Generated by Django 4.2 on 2023-06-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0031_alter_orderunit_infill_alter_orderunit_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='infill_wall_combination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print_order.printunitinfillwallcombination'),
        ),
    ]
