# Generated by Django 4.2 on 2023-06-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0032_orderunit_infill_wall_combination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='infill_wall_combination',
        ),
    ]
