# Generated by Django 4.2 on 2023-06-14 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0033_remove_orderunit_infill_wall_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintUnitWallThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField(help_text='In millimeters', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.3)])),
            ],
        ),
        migrations.AlterField(
            model_name='printunitwall',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
