# Generated by Django 4.2 on 2023-06-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0034_printunitwallthickness_alter_printunitwall_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='wall_thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitwallthickness'),
        ),
    ]
