# Generated by Django 4.2 on 2023-06-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0035_orderunit_wall_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='wall_thickness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='print_order.printunitwallthickness'),
            preserve_default=False,
        ),
    ]
