# Generated by Django 4.2 on 2023-06-14 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0036_alter_orderunit_wall_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='scale',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
