# Generated by Django 4.2 on 2023-06-15 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0037_orderunit_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='scale',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
