# Generated by Django 4.2 on 2023-06-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_printertype_max_print_size_and_more'),
        ('print_order', '0038_alter_orderunit_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='printing_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printer.printingmethod'),
        ),
    ]
