# Generated by Django 4.2 on 2023-06-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0039_orderunit_printing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='eta',
            field=models.DateTimeField(null=True),
        ),
    ]
