# Generated by Django 4.2 on 2023-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_order', '0040_orderunit_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
