# Generated by Django 4.1.3 on 2023-01-04 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0009_alter_like_unique_together_and_more'),
        ('store', '0002_productcategory_productvariation_and_more'),
        ('user_profile', '0016_alter_userprofile_managers_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('awaiting_payment', 'Awaiting Payment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='reviewing', max_length=16)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.billingaddress')),
                ('items', models.ManyToManyField(to='store.productvariationoptioncombination')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.shippingaddress')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.shippingmethod')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.userprofile')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
