# Generated by Django 4.1.3 on 2023-01-08 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
        ('store_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('awaiting_payment', 'Awaiting Payment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='awaiting_payment', max_length=16),
        ),
        migrations.CreateModel(
            name='StoreOrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariationoptioncombination')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_order.storeorder')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='items',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='items',
            field=models.ManyToManyField(through='store_order.StoreOrderUnit', to='store.productvariationoptioncombination'),
        ),
    ]
