# Generated by Django 4.1.3 on 2023-03-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_order', '0002_alter_storeorder_status_storeorderunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('awaiting_payment', 'Awaiting Payment'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='awaiting_payment', max_length=16),
        ),
    ]
