# Generated by Django 4.1.3 on 2023-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_order', '0003_alter_storeorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('rejected', 'Rejected'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='awaiting_payment', max_length=16),
        ),
    ]
