# Generated by Django 4.1.3 on 2022-12-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
