# Generated by Django 4.1.3 on 2022-12-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_address_shippingaddress_billingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='object_id',
        ),
    ]
