# Generated by Django 4.1.3 on 2022-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_shippingmethod_attachmentimage_attachmentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentimage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
