# Generated by Django 4.1.3 on 2022-12-30 22:57

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_attachmentfile_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attachmentfile',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='attachmentimage',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='billingaddress',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='like',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shippingaddress',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shippingmethod',
            managers=[
                ('objectsWithDeleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attachmentimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachmentimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
