# Generated by Django 4.1.3 on 2023-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_attachmentfile_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'content_type', 'object_id'), name='like_unique_undeleted'),
        ),
    ]
