# Generated by Django 4.1.3 on 2023-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_rating_rating_rating_unique_undeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
