# Generated by Django 4.1.3 on 2023-03-08 13:58

from django.db import migrations, models
import spoolio_backend.libs.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_rating_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentfile',
            name='file',
            field=models.FileField(storage=spoolio_backend.libs.storage_backends.PrivateMediaStorage(), upload_to='attachment-files/'),
        ),
        migrations.AlterField(
            model_name='attachmentimage',
            name='image',
            field=models.ImageField(storage=spoolio_backend.libs.storage_backends.PrivateMediaStorage(), upload_to='attachment-images/'),
        ),
    ]
