# Generated by Django 4.1.3 on 2023-03-12 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_billingaddress_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=16),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='vat_id',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='VAT ID is not valid accourding to regular expression rules', regex='(?:(AT)\\s*(U\\d{8}))|(?:(BE)\\s*(0?\\d{*}))|(?:(CZ)\\s*(\\d{8,10}))|(?:(DE)\\s*(\\d{9}))|(?:(CY)\\s*(\\d{8}[A-Z]))|(?:(DK)\\s*(\\d{8}))|(?:(EE)\\s*(\\d{9}))|(?:(GR)\\s*(\\d{9}))|(?:(ES|NIF:?)\\s*([0-9A-Z]\\d{7}[0-9A-Z]))|(?:(FI)\\s*(\\d{8}))|(?:(FR)\\s*([0-9A-Z]{2}\\d{9}))|(?:(GB)\\s*((\\d{9}|\\d{12})~(GD|HA)\\d{3}))|(?:(HU)\\s*(\\d{8}))|(?:(IE)\\s*(\\d[A-Z0-9\\\\+\\\\*]\\d{5}[A-Z]))|(?:(IT)\\s*(\\d{11}))|(?:(LT)\\s*((\\d{9}|\\d{12})))|(?:(LU)\\s*(\\d{8}))|(?:(LV)\\s*(\\d{11}))|(?:(MT)\\s*(\\d{8}))|(?:(NL)\\s*(\\d{9}B\\d{2}))|(?:(PL)\\s*(\\d{10}))|(?:(PT)\\s*(\\d{9}))|(?:(SE)\\s*(\\d{12}))|(?:(SI)\\s*(\\d{8}))|(?:(SK)\\s*(\\d{10}))|(?:\\D|^)(\\d{11})(?:\\D|$)|(?:(CHE)(-|\\s*)(\\d{3}\\.\\d{3}\\.\\d{3}))|(?:(SM)\\s*(\\d{5}))')]),
        ),
    ]
