# Generated by Django 4.1.3 on 2023-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_billingaddress_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=16),
        ),
    ]
