# Generated by Django 4.1.3 on 2023-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_billingaddress_vat_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='like',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='like_unique_undeleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='like_unique'),
        ),
    ]
