# Generated by Django 4.1.3 on 2023-04-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('print_order', '0026_orderunit_screenshot'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration of printing job in seconds')),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('in_queue', 'In queue'), ('in_progress', 'In progress'), ('done', 'Done')], default='in_queue', max_length=16)),
                ('print_order_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_order.orderunit')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
