# Generated by Django 4.1.3 on 2023-04-20 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingjob',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 24, 16, 92224)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printingjob',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 12, 24, 44, 945158)),
            preserve_default=False,
        ),
    ]
