# Generated by Django 4.1.3 on 2022-11-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default='default subtitle', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('3d-printing', '3D Printing'), ('electronics', 'Electronics'), ('design', 'Design')], default='3d-printing', max_length=16),
            preserve_default=False,
        ),
    ]
