# Generated by Django 4.1.3 on 2023-03-08 13:58

from django.db import migrations, models
import spoolio_backend.libs.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=spoolio_backend.libs.storage_backends.PublicMediaStorage(), upload_to='blog_images/'),
        ),
    ]
