# Generated by Django 4.2 on 2023-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_category_alter_blog_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
