# Generated by Django 4.2 on 2023-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printertype',
            name='printing_method',
            field=models.CharField(choices=[('fdm', 'FDM'), ('sla', 'SLA')], default='fdm', max_length=16),
            preserve_default=False,
        ),
    ]
