# Generated by Django 4.2 on 2023-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0010_walls_infillwallscombination'),
        ('printer', '0002_printertype_printing_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printertype',
            name='supported_materials',
        ),
        migrations.CreateModel(
            name='PrintingMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('supported_materials', models.ManyToManyField(to='filament.material')),
            ],
        ),
    ]
