# Generated by Django 4.2 on 2023-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filament', '0011_remove_infillwallscombination_infill_and_more'),
        ('printer', '0003_remove_printertype_supported_materials_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintingMethods',
            new_name='PrintingMethod',
        ),
        migrations.RemoveField(
            model_name='printertype',
            name='printing_method',
        ),
        migrations.AddField(
            model_name='printertype',
            name='supported_materials',
            field=models.ManyToManyField(to='filament.material'),
        ),
    ]
