# Generated by Django 4.2 on 2023-06-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_rename_printingmethods_printingmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printertype',
            name='printing_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='printer.printingmethod'),
        ),
    ]
