# Generated by Django 4.2 on 2023-06-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_printertype_printing_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printertype',
            name='printing_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='printer.printingmethod'),
            preserve_default=False,
        ),
    ]
