# Generated by Django 4.2 on 2023-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_alter_printertype_printing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingmethod',
            name='full_name',
            field=models.CharField(default='abc', max_length=128),
            preserve_default=False,
        ),
    ]
