# Generated by Django 4.2 on 2023-06-06 15:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_printingmethod_precision_printingmethod_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printertype',
            name='max_print_size',
            field=models.CharField(default='250,210,207', help_text='Maximum print size dimenstions. Format: "x,y,z" in millimeters', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printertype',
            name='max_resolution',
            field=models.FloatField(default=0.1, help_text='In millimeters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printertype',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='printer_type_pictures/'),
        ),
    ]
