# Generated by Django 4.1.3 on 2022-12-13 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_profile', '0005_visitor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor',
            new_name='Like',
        ),
    ]
