# Generated by Django 4.1.3 on 2022-12-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_visitor_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='metadata',
        ),
    ]
