# Generated by Django 4.1.3 on 2022-12-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_like_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
