# Generated by Django 4.1.3 on 2022-12-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_address_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
