# Generated by Django 4.1.3 on 2022-12-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
