# Generated by Django 4.1.3 on 2022-12-24 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_billingaddress_content_type_and_more'),
        ('user_profile', '0013_remove_userprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.billingaddress'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.shippingaddress'),
        ),
    ]
