# Generated by Django 4.1.3 on 2022-12-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_userprofile_billing_addresses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='billing_addresses',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='shipping_addresses',
            new_name='shipping_address',
        ),
    ]
