# Generated by Django 4.2 on 2023-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='todo', max_length=256),
            preserve_default=False,
        ),
    ]
